# Generated by Django 3.2.4 on 2021-06-25 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('idPlataforma', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Plataforma')),
                ('nombrePlataforma', models.CharField(max_length=80, verbose_name='Nombre de la Plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Nombre de la Serie')),
                ('genero', models.CharField(blank=True, max_length=80, null=True, verbose_name='Género')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.plataforma')),
            ],
        ),
    ]
