# Generated by Django 3.2.3 on 2021-06-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopsis', models.CharField(max_length=1000, verbose_name='Sinopsis')),
                ('actor1', models.CharField(max_length=1000, verbose_name='Actor 1')),
                ('dactor1', models.CharField(max_length=1000, verbose_name='Descripcion 1')),
                ('iactor1', models.ImageField(upload_to='', verbose_name='Imagen1')),
                ('actor2', models.CharField(max_length=1000, verbose_name='Actor 2')),
                ('dactor2', models.CharField(max_length=1000, verbose_name='Descripcion 2')),
                ('iactor2', models.ImageField(upload_to='', verbose_name='Imagen2')),
                ('actor3', models.CharField(max_length=1000, verbose_name='Actor 3')),
                ('dactor3', models.CharField(max_length=1000, verbose_name='Descripcion 3')),
                ('iactor3', models.ImageField(upload_to='', verbose_name='Imagen3')),
                ('actor4', models.CharField(max_length=1000, verbose_name='Actor 4')),
                ('dactor4', models.CharField(max_length=1000, verbose_name='Descripcion 4')),
                ('iactor4', models.ImageField(upload_to='', verbose_name='Imagen4')),
                ('actor5', models.CharField(max_length=1000, verbose_name='Actor 5')),
                ('dactor5', models.CharField(max_length=1000, verbose_name='Descripcion 5')),
                ('iactor5', models.ImageField(upload_to='', verbose_name='Imagen5')),
                ('actor6', models.CharField(max_length=1000, verbose_name='Actor 6')),
                ('dactor6', models.CharField(max_length=1000, verbose_name='Descripcion 6')),
                ('iactor6', models.ImageField(upload_to='', verbose_name='Imagen6')),
                ('trailer', models.URLField(verbose_name='Trailer')),
                ('desarrollo', models.CharField(max_length=1000, verbose_name='Desarrollo')),
                ('controversias', models.CharField(max_length=1000, verbose_name='Controversia')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.series')),
            ],
        ),
    ]
